---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v3.96.0 # renovate: depName=aquaproj/aqua-registry

packages:
- name: dominikh/go-tools/staticcheck@2022.1.2
- name: goreleaser/goreleaser@v1.15.2
- name: securego/gosec@v2.14.0
- name: reviewdog/reviewdog@v0.14.1
- name: mvdan/sh@v3.6.0
- name: koalaman/shellcheck@v0.9.0
- name: rhysd/actionlint@v1.6.23
- name: takumin/gjson@v0.0.2
- name: aquasecurity/trivy@v0.37.2
- name: x-motemen/gobump@v0.2.0
- name: hashicorp/packer-plugin-sdk/packer-sdc@v0.3.4
