---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v4.327.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: dominikh/go-tools/staticcheck@2024.1.1
- name: goreleaser/goreleaser@v2.6.1
- name: securego/gosec@v2.22.2
- name: reviewdog/reviewdog@v0.20.3
- name: mvdan/sh@v3.10.0
- name: koalaman/shellcheck@v0.10.0
- name: rhysd/actionlint@v1.7.7
- name: takumin/gjson@v0.0.3
- name: aquasecurity/trivy@v0.60.0
- name: x-motemen/gobump@v0.2.0
- name: hashicorp/packer-plugin-sdk/packer-sdc@v0.6.0
- name: hashicorp/packer@v1.11.2
- name: takumin/gyaml@v0.0.2
- name: editorconfig-checker/editorconfig-checker@v3.2.1
- name: go-task/task@v3.41.0
