---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v3.73.0 # renovate: depName=aquaproj/aqua-registry

packages:
- name: dominikh/go-tools/staticcheck@2022.1.2
- name: goreleaser/goreleaser@v1.11.5
- name: securego/gosec@v2.13.1
- name: reviewdog/reviewdog@v0.14.1
- name: mvdan/sh@v3.5.1
- name: koalaman/shellcheck@v0.8.0
- name: rhysd/actionlint@v1.6.21
- name: takumin/gjson@v0.0.2
- name: aquasecurity/trivy@v0.32.1
- name: x-motemen/gobump@v0.2.0
- name: hashicorp/packer-plugin-sdk/packer-sdc@v0.3.2
