---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v4.115.0 # renovate: depName=aquaproj/aqua-registry

packages:
- name: dominikh/go-tools/staticcheck@2023.1.6
- name: goreleaser/goreleaser@v1.23.0
- name: securego/gosec@v2.18.2
- name: reviewdog/reviewdog@v0.16.0
- name: mvdan/sh@v3.7.0
- name: koalaman/shellcheck@v0.9.0
- name: rhysd/actionlint@v1.6.26
- name: takumin/gjson@v0.0.2
- name: aquasecurity/trivy@v0.48.2
- name: x-motemen/gobump@v0.2.0
- name: hashicorp/packer-plugin-sdk/packer-sdc@v0.5.2
