before:
  hooks:
  - go mod download
  - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  - arm64
  flags:
  - -trimpath
  ldflags:
  - -s -w -buildid=
  - -X {{ .ModulePath }}/version.Version={{ .Version }}
  - -X {{ .ModulePath }}/version.Revision={{ .FullCommit }}
  - -X {{ .ModulePath }}/version.VersionPrerelease=
  - -extldflags -static
  mod_timestamp: '{{ .CommitTimestamp }}'
  binary: '{{ .ProjectName }}_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}'
archives:
- name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}'
  format: zip
checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS'
  algorithm: sha256
release:
  prerelease: auto
changelog:
  skip: true
