runner:
  shfmt:
    cmd: shfmt -d .
    format: diff
  shellcheck:
    cmd: shellcheck -f checkstyle $(find '.' -type f -a \( -name '*.sh' -o -name '*.bash' \) -print)
    format: checkstyle
  gjson-validate:
    cmd: gjson validate .
    format: rdjsonl
  gyaml-validate:
    cmd: gyaml validate .
    format: rdjsonl
  actionlint:
    cmd: actionlint -oneline
    errorformat:
    - '%f:%l:%c: %m'
  gofmt:
    cmd: gofmt -d .
    format: diff
  govet:
    cmd: go vet ./...
    format: govet
  gosec:
    cmd: gosec -quiet -fmt golint ./...
    format: gosec
  staticcheck:
    cmd: staticcheck ./...
    format: staticcheck
  editorconfig-checker:
    cmd: ec -no-color
    errorformat:
    - '%-G%+P%f:'
    - '%\s%+%l: %m'
    - '%-Q'
    - '%-G%.%#'
