name: Setup Go
description: Setup Go by reconfigure input values
inputs:
  go-mod:
    description: go.mod file path
    required: false
    default: go.mod
  go-sum:
    description: go.sum file path
    required: false
    default: go.sum
  cache:
    description: actions cache enabled
    required: false
    default: false
  check-latest:
    description: check latest version
    required: false
    default: false
runs:
  using: composite
  steps:
  ################################################################################
  # Setup Go
  ################################################################################
  - name: Setup Go
    uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5
    with:
      go-version-file: ${{ inputs.go-mod }}
      cache: ${{ inputs.cache }}
      cache-dependency-path: ${{ inputs.go-sum }}
      check-latest: ${{ inputs.check-latest }}
