name: Setup Aqua
description: Setup Aqua by using cache and environment variables
runs:
  using: composite
  steps:
  - name: Cache Directory
    id: cache-dir
    shell: bash
    run: echo "aqua=${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}" >> $GITHUB_OUTPUT
  - name: Aqua Tools Cache
    uses: actions/cache@v4
    with:
      path: ${{ steps.cache-dir.outputs.aqua }}
      key: aqua-tools-${{ runner.os }}-${{ hashFiles('**/.aqua.yaml') }}
  - name: Setup Aqua
    uses: aquaproj/aqua-installer@v3.0.1
    with:
      aqua_version: v2.28.1
      aqua_opts: -a
