name: Renovate Config Validator
on:
  workflow_call:
    inputs:
      jobname:
        type: string
        required: false
        description: 'A jobname passed from the caller workflow'
        default: 'renovate-config-validator'
  pull_request:
    paths:
    - '.renovaterc.json'
    - '.github/workflows/renovate-config-validator.yml'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || inputs.jobname }}
  cancel-in-progress: true
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - name: Checkout
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
    - name: Setup Node.js
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
      with:
        node-version: 'lts/*'
        cache: 'npm'
        cache-dependency-path: '.renovaterc.json'
    - name: Renovate Config Validator
      run: npx --yes --package renovate -- renovate-config-validator --strict
