name: Renovate Config Validator
on:
  workflow_call:
    inputs:
      jobname:
        type: string
        required: false
        description: 'A jobname passed from the caller workflow'
        default: 'renovate-config-validator'
  pull_request:
    paths:
    - '.renovaterc.json'
    - '.github/workflows/renovate-config-validator.yml'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || inputs.jobname }}
  cancel-in-progress: true
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
    - name: Setup Node.js
      uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
      with:
        node-version: 'lts/*'
        cache: 'npm'
        cache-dependency-path: '.renovaterc.json'
    - name: Renovate Config Validator
      run: npx --yes --package renovate -- renovate-config-validator --strict
