name: Reviewdog (actionlint)
on:
  workflow_call:
    inputs:
      jobname:
        type: string
        required: false
        description: 'A jobname passed from the caller workflow'
        default: 'reviewdog-actionlint'
  pull_request:
    paths:
    - '.aqua.yaml'
    - '.reviewdog.yml'
    - '.github/actions/*.yml'
    - '.github/actions/*.yaml'
    - '.github/workflows/*.yml'
    - '.github/workflows/*.yaml'
permissions:
  checks: write
  contents: read
  pull-requests: write
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || inputs.jobname }}
  cancel-in-progress: true
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - name: Checkout
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
    - name: Setup Go
      uses: ./.github/actions/setup-go
    - name: Setup Aqua
      uses: ./.github/actions/setup-aqua
    - name: Setup Reviewdog
      id: reviewdog
      uses: ./.github/actions/setup-reviewdog
    - name: Reviewdog
      run: reviewdog -runners 'actionlint' -reporter '${{ steps.reviewdog.outputs.reporter }}' -filter-mode 'nofilter' -fail-on-error
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
